//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzON.Negocio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int id { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public string portal { get; set; }
        public Nullable<int> piso { get; set; }
        public string puerta { get; set; }
        public string localidad { get; set; }
        public int cliente { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
    }
}
