//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzON.Negocio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public string CIF { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string horario { get; set; }
        public Nullable<int> telefono_reparto { get; set; }
        public Nullable<int> telefono_restaurante { get; set; }
    }
}
