//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzON.Negocio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int numero_telefono { get; set; }
        public string tipo_numero { get; set; }
        public int cliente { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
    }
}
